# Generated by Django 4.1.2 on 2022-10-23 18:28

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('is_feature', models.BooleanField()),
                ('title', models.CharField(max_length=100)),
                ('intro', models.TextField()),
                ('body', models.TextField()),
                ('quote', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Blogs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=None)),
                ('image2', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_img', force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[100, 100], upload_to='whatever')),
                ('alt_text', models.CharField(max_length=100)),
                ('is_lead', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('is_heading', models.BooleanField()),
                ('is_feature', models.BooleanField()),
                ('is_footing', models.BooleanField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_image', to='blog.blog')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='blog.category'),
        ),
    ]
