# Generated by Django 4.1.2 on 2022-10-24 23:20

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blogimage',
            name='image2',
        ),
        migrations.AddField(
            model_name='blogimage',
            name='large_image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_img', force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[1920, 900], upload_to='bloglarge'),
        ),
        migrations.AddField(
            model_name='blogimage',
            name='lead_image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_img', force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[380, 470], upload_to='blogsmall'),
        ),
        migrations.AddField(
            model_name='blogimage',
            name='small_image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_img', force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[300, 400], upload_to='blogsmall'),
        ),
    ]
