# Generated by Django 4.1.2 on 2022-10-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LipaNaMpesaOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_request_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('merchant_request_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('result_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_number', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_date', models.DateTimeField()),
                ('phone_number', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Lipa Na Mpesa Online',
            },
        ),
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('phone_number', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.TextField()),
                ('organization_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.TextField()),
            ],
            options={
                'verbose_name': 'Mpesa Payment',
                'verbose_name_plural': 'Mpesa Payments',
            },
        ),
    ]
