# Generated by Django 4.1.2 on 2022-10-24 23:20

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image2',
        ),
        migrations.AddField(
            model_name='productimage',
            name='feature_image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_img', force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[300, 400], upload_to='shopfeature'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='shop_image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_img', force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[350, 450], upload_to='shopshop'),
        ),
    ]
