# Generated by Django 4.1.2 on 2022-10-23 18:28

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('end_date', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'Layout',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Socials',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='LayoutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='layout/default.jpg', upload_to='layout')),
                ('image2', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_img', force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[100, 100], upload_to='whatever')),
                ('alt_text', models.CharField(max_length=100)),
                ('is_header', models.BooleanField()),
                ('is_deals', models.BooleanField()),
                ('is_footer', models.BooleanField()),
                ('is_breadcrumb', models.BooleanField()),
                ('is_logo', models.BooleanField()),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout_image', to='layout.layout')),
            ],
        ),
    ]
