# Generated by Django 4.1.2 on 2022-10-24 23:20

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layoutimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='layoutimage',
            name='image2',
        ),
        migrations.AddField(
            model_name='layoutimage',
            name='bread_image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_img', force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[1920, 620], upload_to='breadcrumbimages'),
        ),
        migrations.AddField(
            model_name='layoutimage',
            name='deal_image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_img', force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[1920, 620], upload_to='dealsimages'),
        ),
        migrations.AddField(
            model_name='layoutimage',
            name='foot_image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_img', force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[1920, 520], upload_to='footerimages'),
        ),
        migrations.AddField(
            model_name='layoutimage',
            name='head_image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_img', force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[1920, 920], upload_to='headerimages'),
        ),
    ]
